yarnPath: .yarn/releases/yarn-rc.js

packageExtensions:
  "@shelf/jest-mongodb@*":
    peerDependencies:
      "jest-environment-node": "*"
  "moleculer@*":
    peerDependenciesMeta:
      "winston":
        "optional": true
  "sequelize@*":
    peerDependenciesMeta:
      "mysql2":
        "optional": true
  "@angular-devkit/architect@*":
    peerDependencies:
      "@angular-devkit/build-angular": "*"
  "debug@*":
    dependencies:
      "supports-color": "*"
