packageExtensions:

# Fixes for Angular
  "@angular-devkit/architect@*":
    peerDependencies:
      "@angular-devkit/build-angular": "*"
  "@angular/platform-browser@*":
    peerDependencies:
      "@angular/animations": "*"
  "ngx-date-fns@*":
    peerDependencies:
      "rxjs": "*"
  "ng-pick-datetime@*":
    peerDependencies:
      "@angular/animations": "*"
      "@angular/common": "*"
      "@angular/core": "*"
      "@angular/forms": "*"
      "rxjs": "*"
  "angular2-recaptcha@*":
    peerDependencies:
      "@angular/core": "*"
      "@angular/forms": "*"
      "rxjs": "*"
  "@angular/cdk@*":
    peerDependencies:
      "rxjs": "*"
  "@angular/material@*":
    peerDependencies:
      "rxjs": "*"
      "@angular/platform-browser": "*"
  "@bugsnag/plugin-angular@*":
    peerDependencies:
      "@angular/core": "*"
      "@bugsnag/js": "*"

# Fixes for backend
  "@shelf/jest-mongodb@*":
    peerDependencies:
      jest-environment-node: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  moleculer@*:
    peerDependenciesMeta:
      winston:
        optional: true
  sequelize@*:
    peerDependenciesMeta:
      mysql2:
        optional: true

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-angular.js
    spec: "https://github.com/bgotink/yarn-plugin-angular/raw/master/bin/%40yarnpkg/plugin-angular.js"

yarnPath: .yarn/releases/yarn-rc.js
